// Precomputes globe geometry so the runtime ships no geo libraries.
// Emits src/geo-data.js: a land-dot mask, the Saudi outline, and regional neighbours.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { feature } from 'topojson-client';

const here = path.dirname(fileURLToPath(import.meta.url));
const world = JSON.parse(fs.readFileSync(path.join(here, 'countries-50m.json'), 'utf8'));
const countries = feature(world, world.objects.countries).features;

const SAUDI_ID = '682';
// Everything that shares a horizon with the Kingdom, for context on the zoom-in.
const NEIGHBOUR_IDS = new Set([
  '818', '400', '368', '414', '634', '784', '512', '887', '760', '364', '232', '232', '729',
]);

/* ---------- ring extraction + bbox index ---------- */

function ringsOf(geometry) {
  const out = [];
  if (!geometry) return out;
  if (geometry.type === 'Polygon') out.push(...geometry.coordinates);
  else if (geometry.type === 'MultiPolygon') for (const poly of geometry.coordinates) out.push(...poly);
  return out;
}

function bbox(ring) {
  let x0 = Infinity, y0 = Infinity, x1 = -Infinity, y1 = -Infinity;
  for (const [x, y] of ring) {
    if (x < x0) x0 = x;
    if (x > x1) x1 = x;
    if (y < y0) y0 = y;
    if (y > y1) y1 = y;
  }
  return [x0, y0, x1, y1];
}

// Ray casting in lon/lat space — accurate enough at the scale we sample.
function inRing(lon, lat, ring) {
  let inside = false;
  for (let i = 0, j = ring.length - 1; i < ring.length; j = i++) {
    const xi = ring[i][0], yi = ring[i][1];
    const xj = ring[j][0], yj = ring[j][1];
    if ((yi > lat) !== (yj > lat) && lon < ((xj - xi) * (lat - yi)) / (yj - yi) + xi) inside = !inside;
  }
  return inside;
}

const landRings = [];
for (const f of countries) {
  for (const ring of ringsOf(f.geometry)) landRings.push({ ring, bb: bbox(ring) });
}

/* ---------- land dot mask on a fibonacci sphere ---------- */
// Even spacing everywhere, unlike a lat/lon grid which bunches at the poles.

const N = 42000;
const GOLDEN = Math.PI * (3 - Math.sqrt(5));
const dots = [];

for (let i = 0; i < N; i++) {
  const y = 1 - (i / (N - 1)) * 2;
  const r = Math.sqrt(Math.max(0, 1 - y * y));
  const theta = GOLDEN * i;
  const x = Math.cos(theta) * r;
  const z = Math.sin(theta) * r;

  const lat = (Math.asin(y) * 180) / Math.PI;
  const lon = (Math.atan2(z, x) * 180) / Math.PI;

  let hit = false;
  for (const { ring, bb } of landRings) {
    if (lon < bb[0] || lon > bb[2] || lat < bb[1] || lat > bb[3]) continue;
    if (inRing(lon, lat, ring)) { hit = true; break; }
  }
  if (hit) dots.push(+lon.toFixed(2), +lat.toFixed(2));
}

/* ---------- outlines ---------- */

const simplify = (ring, tol) => {
  // Drop points closer than tol degrees; keeps outlines light without visible loss.
  const out = [ring[0]];
  for (let i = 1; i < ring.length; i++) {
    const [px, py] = out[out.length - 1];
    const [x, y] = ring[i];
    if (Math.abs(x - px) > tol || Math.abs(y - py) > tol) out.push([+x.toFixed(3), +y.toFixed(3)]);
  }
  if (out.length > 2) out.push(out[0]);
  return out;
};

const saudiFeature = countries.find((f) => String(f.id) === SAUDI_ID);
const saudi = ringsOf(saudiFeature.geometry)
  .filter((r) => r.length > 12)
  .map((r) => simplify(r, 0.05));

const neighbours = countries
  .filter((f) => NEIGHBOUR_IDS.has(String(f.id)))
  .flatMap((f) => ringsOf(f.geometry))
  .filter((r) => r.length > 24)
  .map((r) => simplify(r, 0.12));

// Kingdom bounds, so the camera framing is derived rather than eyeballed.
let bx0 = Infinity, by0 = Infinity, bx1 = -Infinity, by1 = -Infinity;
for (const ring of saudi) {
  for (const [x, y] of ring) {
    if (x < bx0) bx0 = x; if (x > bx1) bx1 = x;
    if (y < by0) by0 = y; if (y > by1) by1 = y;
  }
}

const out = `// Generated by tools/build-geo.js — do not edit by hand.
// Source: Natural Earth 1:50m via world-atlas.
export const LAND_DOTS = new Float32Array(${JSON.stringify(dots)});
export const SAUDI_RINGS = ${JSON.stringify(saudi)};
export const NEIGHBOUR_RINGS = ${JSON.stringify(neighbours)};
export const SAUDI_BOUNDS = ${JSON.stringify([+bx0.toFixed(3), +by0.toFixed(3), +bx1.toFixed(3), +by1.toFixed(3)])};
// Al-Qassim — the office's own coordinates, and the core of the fingerprint.
export const QASSIM = [43.9738, 26.3442];
`;

fs.writeFileSync(path.join(here, '..', 'src', 'geo-data.js'), out);
console.log(
  `dots: ${dots.length / 2}  saudi rings: ${saudi.length}  neighbour rings: ${neighbours.length}  bounds: ${[bx0, by0, bx1, by1].map((n) => n.toFixed(2)).join(', ')}`
);
